// Contract addresses + minimal ABIs for the frontend.
//
// After running `npx hardhat run scripts/deploy.js --network localhost`, paste
// the printed addresses here. The role wallet addresses are the default Hardhat
// accounts in order: index 0 = admin, 1 = Sales, 2 = Supplier, 3 = Dispatch,
// 4 = Driver, 5 = Customer.

export const ORDER_CONTRACT_ADDRESS    = "0x0000000000000000000000000000000000000000"; // TODO paste from deploy
export const DELIVERY_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"; // TODO paste from deploy

export const HARDHAT_CHAIN_ID = 31337;
export const HARDHAT_RPC      = "http://127.0.0.1:8545";

// Trim ABIs — full ABIs are generated by Hardhat in /artifacts/.
// Person B: import the full JSON from artifacts when wiring up real calls.
export const ORDER_ABI = [
  "function createOrder(address supplier, tuple(string sku, uint256 quantity)[] items, uint256 deliveryDate) returns (uint256)",
  "function getOrder(uint256 orderId) view returns (tuple(uint256 id, address buyer, address supplier, tuple(string sku, uint256 quantity)[] items, uint8 status, uint256 deliveryDate, uint256 createdAt))",
  "function getRole(address account) view returns (uint8)",
  "event OrderCreated(uint256 indexed orderId, address indexed buyer, address indexed supplier)",
];

export const DELIVERY_ABI = [
  "function scanPallet(uint256 orderId, tuple(string sku, uint256 quantity)[] scanned)",
  "function confirmDelivery(uint256 orderId)",
  "function getDelivery(uint256 orderId) view returns (tuple(uint256 orderId, address driver, uint8 status, uint256 verifiedAt, uint256 confirmedAt))",
  "event PalletScanned(uint256 indexed orderId, address indexed driver, bool matched)",
  "event DiscrepancyDetected(uint256 indexed orderId, address indexed driver, string reason)",
  "event DeliveryConfirmed(uint256 indexed orderId, address indexed driver)",
];

export const ROLE_NAMES = ["None", "Sales", "Supplier", "Dispatch", "Driver", "Customer"];
